_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  announcements_feed: 0
  automated_cron: 0
  backup_migrate: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  graphql: 0
  graphql_composable: 0
  graphql_compose: 0
  graphql_compose_blocks: 0
  graphql_compose_comments: 0
  graphql_compose_edges: 0
  graphql_compose_image_style: 0
  graphql_compose_layout_builder: 0
  graphql_compose_layouts: 0
  graphql_compose_menus: 0
  graphql_compose_routes: 0
  graphql_compose_users: 0
  graphql_compose_views: 0
  graphql_examples: 0
  help: 0
  history: 0
  image: 0
  jsonapi: 0
  jsonapi_defaults: 0
  jsonapi_extras: 0
  jsonapi_hypermedia: 0
  jsonapi_menu_items: 0
  jsonapi_menu_items_hypermedia: 0
  jsonapi_resources: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  openapi: 0
  openapi_jsonapi: 0
  openapi_rest: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  responsive_image: 0
  rest: 0
  restui: 0
  schemata: 0
  schemata_json_schema: 0
  search: 0
  serialization: 0
  shortcut: 0
  simplenews: 0
  simplenews_demo: 0
  standard: 0
  svg_image: 0
  svg_image_responsive: 0
  symfony_mailer: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  typed_data: 0
  user: 0
  views_ui: 0
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
theme:
  olivero: 0
  claro: 0
profile: standard
