display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 'लागू करें'
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
      pager:
        options:
          tags:
            previous: '‹ पिछले'
            next: 'अगला >'
            first: '« प्रथम'
            last: 'अन्तिम »'
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
      fields:
        mail:
          label: ईमेल
        user_name:
          label: 'प्रयोक्ता का नाम'
        subscriptions_target_id:
          separator: ', '
        status:
          label: अवस्था
          separator: ', '
        created:
          label: निर्मित
        operations:
          label: कार्यवाही
      filters:
        mail:
          expose:
            label: ईमेल
        status:
          expose:
            label: अवस्था
  page_1:
    display_title: पृष्ठ
