name: OpenAPI REST
description: OpenAPI support for the REST module.
type: module
package: Web Services
core: 8.x
core_version_requirement: ^8 || ^9 || ^10
dependencies:
  - drupal:rest
  - openapi:openapi (>=8.x-2.0-rc1)
  - schemata:schemata
  - schemata:schemata_json_schema


# Information added by Drupal.org packaging script on 2022-12-06
version: '8.x-2.0-rc3'
project: 'openapi_rest'
datestamp: 1670346530
